export const MOCK_RESUME_DATA = {
  resume: {
    id: 'res-001',
    title: '만들면서 행복을 찾는 백엔드 개발자, 황선우',
    bio: 'Kotlin과 Go를 주력으로 사용하는 5년 차 개발자입니다. 게임 전적 검색 서비스부터 지도 기반 소셜 앱까지 다양한 도메인에서 백엔드 시스템을 구축해 왔습니다. 단순히 기능 구현에 그치지 않고, 실시간 랭킹 시스템 설계나 데이터 시각화 등 기술을 통해 사용자 경험을 개선하는 과정에서 즐거움을 느낍니다.',
    public: true,
    template: 'modern',
    skills: [
      'Kotlin',
      'Go',
      'Spring Boot',
      'TypeScript',
      'React',
      'Next.js',
      'PostgreSQL',
      'Docker',
    ],
    createdAt: '2023-10-01T09:00:00Z',
    updatedAt: '2026-01-30T22:44:00Z',
    educations: [
      {
        id: 'edu-1',
        school: '대덕소프트웨어마이스터고등학교',
        major: '정보보안과',
        degree: '중퇴',
        startDate: '2018-03',
        endDate: '2019-06',
        gpa: '',
        activities: '',
      },
      {
        id: 'edu-2',
        school: '경상남도 고졸 검정고시',
        major: '',
        degree: '합격',
        startDate: '2020',
        endDate: '2020',
        gpa: '',
        activities: '',
      },
      {
        id: 'edu-3',
        school: '소프트웨어마에스트로 11기',
        major: '',
        degree: '수료',
        startDate: '2020-05',
        endDate: '2020-12',
        gpa: '',
        activities: '스팸 탐지 시스템 ‘Spree’ 개발',
      },
      {
        id: 'edu-4',
        school: '차세대 보안리더 양성프로그램(BoB) 8기',
        major: '보안제품개발트랙',
        degree: '수료',
        startDate: '2019-07',
        endDate: '2020-03',
        gpa: '',
        activities: '무선 네트워크 학습 및 빌드 서버용 보안 시스템 개발 참여',
      },
    ],
    experiences: [
      {
        id: 'exp-1',
        company: '일로아 (iloa.gg)',
        title: 'Backend Developer',
        location: '',
        startDate: '2024-01',
        endDate: '현재',
        description:
          'Kotlin과 Spring Boot를 활용한 백엔드 시스템 개발. 게임 캐릭터 수집품 데이터 파싱 및 실시간 랭킹 처리 시스템 구현, 캐릭터 전투력 수치화 로직 개발 담당.',
      },
      {
        id: 'exp-2',
        company: '㈜코스디자인',
        title: 'Fullstack Engineer',
        location: '',
        startDate: '2020-04',
        endDate: '2023-10',
        description:
          'Node.js(Koa) 및 Kotlin(Ktor) 기반 백엔드 개발. 사용자 인증 시스템(JWT/OAuth), 즉석 만남 서비스 ‘코스밋’ 및 리워드 시스템 개발. React 웹 및 SwiftUI iOS 앱 개발 참여.',
      },
    ],
    projects: [
      {
        id: 'proj-1',
        title: 'Iloa.gg (로스트아크 전적 검색)',
        startDate: '2024-01',
        endDate: '현재',
        description:
          'Lost Ark API를 활용한 실시간 랭킹 시스템 및 데이터 수치화 로직 개발. 사용자 경험 개선을 위한 실시간 핫픽스 및 버그 대응.',
        skills: ['Kotlin', 'Spring', 'PostgreSQL', 'React', 'Next.js'],
        url: 'https://iloa.gg/',
      },
      {
        id: 'proj-2',
        title: 'Gin-Restful (Open Source Library)',
        startDate: '2025-09',
        endDate: '현재',
        description:
          'Go Gin 프레임워크 기반의 RESTful API 개발을 간소화하는 라이브러리. CRUD 기능을 추상화하여 개발 속도 향상.',
        skills: ['Go', 'Gin'],
        url: 'https://github.com/hwangseonu/gin-restful',
      },
      {
        id: 'proj-3',
        title: 'Spree (스팸 메일 탐지 시스템)',
        startDate: '2020-05',
        endDate: '2020-12',
        description:
          'TensorFlow 모델을 FastAPI로 서빙하는 API 개발 및 D3.js를 활용한 탐지 결과 시각화 웹 페이지 개발.',
        skills: ['Python', 'FastAPI', 'TensorFlow', 'React', 'D3.js'],
        url: '',
      },
    ],
  },
}
